### ISSUE TITLE
Fail to configure speech resource: Error: [UserError] failToFindSubscription

### ISSUE THREAD

**Issue by randriksen** [microsoft/AzureAISpeechToolKit#33] opened 2024-10-29 14:13 UTC
Getting this error: Fail to configure speech resource: Error: [UserError] failToFindSubscription
When trying to configure speech resource.

Not really sure why.

**Comment by dilin-MS2** [comment] 2024-10-29 19:29
Hi @randriksen , this usually happens when user accidentally cancel the process when extension tries to fetch subscription list. This process sometimes can be slow, we have a processing bar indicating `'Fetching Azure subscriptions...'` Please wait a while for the list retrival.  If you haven't interact the process but still see this error, please list your reproduce steps. Thanks!

**Comment by randriksen** [comment] 2024-10-30 07:59
It fails at the Fetching Azure subscriptions almost instantly. 
I sign in, and try to configure speech resources, and then it just fails.
I have speech resources configured in Azure, i have contributor access to a subscription. And when testing with PowerShell i can see 3 different subscriptions. 
I can give you a screen recording if you want, but i don't feel like posting it here since you can see my username in the sign-in pulldown.
The extension version I'm using is v0.0.4.

I have a feeling this has something to do with rights, but I'm not completely sure.

**Comment by dilin-MS2** [comment] 2024-10-30 09:29
Hi @randriksen , can you see subscriptions listed in the extension speech resource tree view after logged in?
![Image](https://github.com/user-attachments/assets/34001489-cc0f-4840-a9a4-86e2f6bfedbc)

**Comment by randriksen** [comment] 2024-10-30 10:38
resources doesn't show anything interesting: ![Image](https://github.com/user-attachments/assets/50d5e7a7-e12a-48ac-b68e-12293b3518aa)

steps to reproduce:
sign in: ![Image](https://github.com/user-attachments/assets/9c6d335f-e533-4c60-a80f-e28a0938306f)
allow: ![Image](https://github.com/user-attachments/assets/c7e4f19c-3fbf-432b-a58d-52fd2160ad0b)
choose correct account in dropdown: ![Image](https://github.com/user-attachments/assets/b1a77828-4aee-4231-9d8c-5134f42123c7)

and then it fails: ![Image](https://github.com/user-attachments/assets/02bf7e66-d6a7-48a9-ae78-cbb764e376dd)
it fails in less than 3 seconds.

**Comment by dilin-MS2** [comment] 2024-10-30 18:23
Thanks for the detailed steps. There seems to be some issue fetching your subscription list. How many tenants does your account have? When you go to Azure portal and log in your account, how many subscriptions are listed under your default tenant (directory)?

**Comment by randriksen** [comment] 2024-10-31 08:14
So, My account is tied to 2 tenants. 
In the default tenant I see 3 subscriptions in the azure portal, but i only have rights to do anything into one of them. 
In the other tenant it's just a guest user for teams access.

This is what i get in the developer console:
<html>
<body>

@ | event.ts:1278
-- | --
  | addNotification | @ | notifications.ts:228
  | notify | @ | notificationService.ts:253
  | (anonymous) | @ | mainThreadMessageService.ts:86
  | f | @ | mainThreadMessageService.ts:51
  | $showMessage | @ | mainThreadMessageService.ts:45
  | S | @ | rpcProtocol.ts:458
  | Q | @ | rpcProtocol.ts:443
  | M | @ | rpcProtocol.ts:373
  | L | @ | rpcProtocol.ts:299
  | (anonymous) | @ | rpcProtocol.ts:161
  | B | @ | event.ts:1243
  | fire | @ | event.ts:1274
  | fire | @ | ipc.net.ts:652
  | l.onmessage | @ | localProcessExtensionHost.ts:378


</body>
</html>

Can't find a proper error about anything dealing with the subscription or extension

**Comment by randriksen** [comment] 2024-10-31 08:19
I saw that there was a new version of the extension out, so I've now updated to v0.0.5 
It now gives a different error:
Fail to configure speech resource: Error: SelectSubscriptionError

This is what's in the developer console:
<html>
<body>

B | @ | event.ts:1243
-- | -- | --
  | C | @ | event.ts:1254
  | fire | @ | event.ts:1278
  | addNotification | @ | notifications.ts:228
  | notify | @ | notificationService.ts:253
  | (anonymous) | @ | mainThreadMessageService.ts:86
  | f | @ | mainThreadMessageService.ts:51
  | $showMessage | @ | mainThreadMessageService.ts:45
  | S | @ | rpcProtocol.ts:458
  | Q | @ | rpcProtocol.ts:443
  | M | @ | rpcProtocol.ts:373
  | L | @ | rpcProtocol.ts:299
  | (anonymous) | @ | rpcProtocol.ts:161
  | B | @ | event.ts:1243
  | fire | @ | event.ts:1274
  | fire | @ | ipc.net.ts:652
  | l.onmessage | @ | localProcessExtensionHost.ts:378


</body>
</html>

**Comment by BinarywoodB** [comment] 2024-10-31 20:56
Hi @randriksen , can you check on [azure portal](https://ms.portal.azure.com/#settings/directory) that your account has switch to the tenant with feasible subscription, and also set the startup directory to the same tenant?
![Image](https://github.com/user-attachments/assets/2e0b3a8f-0b74-4e93-bcc3-f3081f7ac1e1)

**Comment by randriksen** [comment] 2024-11-01 09:29
I've made sure the startup directory is the correct one, and that the correct tenant is selected as current. 
There's no difference in the behavior. 
I don't think the problem is connected to the tenant, but rather somehow the subscription

**Comment by dilin-MS2** [comment] 2024-11-02 00:44
Hi @randriksen  Please try the latest v0.0.6 to see if that resolves your issue. Thanks!

**Comment by randriksen** [comment] 2024-11-04 11:05
No difference on v0.0.6

**Comment by randriksen** [comment] 2024-11-05 09:10
Is there some way to get better error messages? It would be really nice to debug this.

**Comment by dilin-MS2** [comment] 2024-11-05 22:54
Hi @randriksen , thank you for actively trying out this extension - really appreciate it!

A more detailed error message is on our backlog and will be included in a future release. Until then, we’ll need to use other methods to understand what’s happening.

1. `SelectSubscriptionError` and `failToFindSubscription` indicate different error scenarios:
    - `SelectSubscriptionError`: This occurs when the login is unsuccessful.
    - `failToFindSubscription`: This occurs when login is successful, but the extension, using the VS Code session credentials, retrieves an empty list of subscriptions for your account. If you’re logged into an Azure account where the default tenant has accessible subscriptions, the extension should be able to fetch them accordingly.

    With the current v0.0.6 extension, are you consistently seeing only the SelectSubscriptionError error? Also, what’s the account status in the VS Code account center?
    ![Image](https://github.com/user-attachments/assets/d0c37e43-4253-47e6-b737-52fc930ede85)

  
2. The log you pasted for "Help -> Toggle Developer Tools" seems not what I am expected:
    
    ![Image](https://github.com/user-attachments/assets/f00f94b4-883f-4923-962f-bc88e0c33450)

3. Is this how the resource tree view look like after you get the error message?
 ![Image](https://github.com/user-attachments/assets/d5c8152f-8b1a-43c5-a159-5b3fd0668bf6)

**Comment by randriksen** [comment] 2024-11-06 07:45
1. The error is Fail to configure speech resource: Error: [UserError] failToFindSubscription
![Image](https://github.com/user-attachments/assets/b5fd0cd2-4377-46ff-8eb3-0459bd936c58)
And this is what the account center looks like:
![Image](https://github.com/user-attachments/assets/31abb699-ac74-4b9a-b378-a14e910fc06e)


2. This is how the developer console looks after i try to configure a speech resource.
 ![Image](https://github.com/user-attachments/assets/c9a4b708-4843-4caa-a73b-778c6af611b6)

3. Yes. That's what the resource tree looks like.
![Image](https://github.com/user-attachments/assets/e3b52fd5-331d-4f11-9a0d-ade03cc9dcbf)

**Comment by dilin-MS2** [comment] 2024-11-06 17:19
I notice that you have several account signed in. Could you try log out all accounts and sign in only the one that you would like to interact with Azure AI Speech Toolkit extension?

**Comment by randriksen** [comment] 2024-11-07 12:45
That seems to have helped :) But it's a bit impractical not to be able to use copilot at the same time.

**Comment by dilin-MS2** [comment] 2024-11-07 17:54
Good to know we found a way to unblock your process.

The extension should allow you to log in to both your GitHub account (for Copilot) and your Microsoft Azure account simultaneously. You can log in to **one** Azure account and possibly multiple GitHub accounts without issue. However, using more than one Azure account hasn't been tested. This might explain the issue with fetching subscriptions—it's possible that the VS Code session is using the credentials from a different Azure account, leading to a failure in retrieving the subscription list.

**Comment by dilin-MS2** [comment] 2024-11-07 17:55
@randriksen  Where do you find a entry point to login 2 Microsoft Azure accounts, please? Let me see whether we can do something to cover this multi-azure-accounts cases.

**Closed** 2024-11-11 09:34 UTC
